name: Flutter_BoilerPlate_With_Auth
description:  A  flutter project implementing login mechanism and the minimum effort to reach code base for a flutter huge sized project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  editable: "^1.1.4"  
  csv: ^5.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  auto_route_generator: ^4.0.0
  path_provider: ^2.0.9
  flutter_services_binding: ^0.1.0
  hydrated_bloc: ^7.0.1
  flutter_bloc: ^7.0.1
  oauth2: ^2.0.0
  flutter_inappwebview:
  formz: ^0.4.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  json_to_model:
  http:
  meta: ^1.2.4
  flutter_typeahead: ^4.0.0
  connectivity: ^3.0.2
  fluttertoast: 8.0.3
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^4.1.0
  flag: ^5.0.1
  responsive_framework: ^0.1.4
  auto_route: ^4.0.1
  flutter_web_auth: ^0.4.1
 

  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.1.6
 
flutter:
  uses-material-design: true
  assets:
    - assets/images/

